### ISSUE TITLE
Add wrapper for redux-saga?

### ISSUE THREAD

**Issue by joffrey-bion** [JetBrains/kotlin-wrappers#107]
[Redux saga](https://redux-saga.js.org/) is a library that allows to integrate side-effects in a redux architecture in a clean fashion.

It makes use of [JavaScript generators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators) to decouple the execution of the side effects from the business logic that decides which side effects to perform.

I'm not sure if this library should be wrapped or if it actually deserves a re-implementation in Kotlin using suspending functions and coroutines. What do you guys think?

**Comment by eugenio1590** [comment]
It is a good question. I think [a service layer](https://github.com/Kotlin/kotlin-full-stack-application-demo/blob/master/client/src/main/kotlin/services/UserService.kt) with Coroutines can replace redux-saga in this case. Of course, the components will depend on the service layer but can be fixed with a facade interface. It is not the best solution, I know. But It can help while redux-saga support or something similar is implemented.

Currently, I thought to use redux-saga but it is difficult to implement in javascript and call this in the Kotlin code.

**Comment by rtatarinov** [comment]
Any updates? I checked this repository and I can't see wrapper for any react effector library..
