### ISSUE TITLE
objectAssign broken in kotlin-extensions

### ISSUE THREAD

**Issue by Jamdan2** [JetBrains/kotlin-wrappers#109]
When `objectAssign()` is used the following error occurs:
```
Module not found: Error: Can't resolve 'core-js/features/object/assign'
```
It would appear that there is no `/features/object/assign` inside of `core-js`, but there is a `/fn/object/assign` which I think is what is needed.

**Comment by Jamdan2** [comment]
I am using the latest version of `kotlin-extensions` which is `1.0.1-pre.34-kotlin-1.3.31`

**Comment by Leonya** [comment]
Make sure you have `core-js@3` installed.

**Comment by toddATavail** [comment]
I am also having this issue, with `1.0.1-pre.87-kotlin-1.3.50`. I am trying to avoid using `npm` directly, relying on Gradle instead as my build system. Do I need to use something like [gradle-node-plugin](https://github.com/srs/gradle-node-plugin) in order to install and manage the `core-js@3` dependency? It seems obvious that something is broken with the process though if `kotlin-extensions` fails when I obtain it via Gradle; there should be some established build dependencies that automatically address this issue, or, at the least, instructions about what else a user must do manually in order to achieve success. Hopefully you can point me in the right direction to resolve this issue. Thanks in advance!
