### ISSUE TITLE
New React Hooks, "Invalid hook call. Hooks can only be called inside of the body of a function component"

### ISSUE THREAD

**Issue by SorenV** [JetBrains/kotlin-wrappers#127]
Verified the react versions were latest.
Verified there wasn't two running instances of react.
Looked at the generated js and it seems (?) that it is calling the hook in the right place.

Min Reproduction: https://github.com/SorenV/min_reproduction-kotlin_react_hooks.

New to a lot of this so might be a gradle config issue as well.  Thanks!

**Comment by Skolotsky** [comment]
It's because raw RBuilder function isn't functional component - it's return value isn't react nodes.
You should use something like this
```kotlin
val renderCount = functionalComponent<RProps> {
    val (count, setCount) = useState(0)
    useEffect {
        console.log("useEffect $count")
    }
    +"count $count"
    button {
        attrs {
            onClickFunction = {
                setCount(count + 1)
            }
        }
    }
}

fun RBuilder.renderCount() {
    child(renderCount)
}
```
where val renderCount - is valid functional component

**Comment by SorenV** [comment]
Thank you!  I was not aware of `functionalComponent`.  I will need to spend a bit more time in the source code I think.  Much appreciated!

**Comment by ffactory-ofcl** [comment]
Oh my god **finally.** Thank you so much.
I've spent hours trying to fix this, wondering about different/conflicting versions of react, react-dom, react-router-dom and their kotlin wrappers. I've reinstalled all of them at least once, specifying versions and stuff. Turns out I just broke the rule of hooks 🙄. Thanks for your help.

**Comment by Ribesg** [comment]
I'm encountering this issue too but I'm using a functional component, maybe I don't understand something, I don't know. My code is here https://github.com/Ribesg/Kita/tree/feature/init

**Comment by Skolotsky** [comment]
@Ribesg, AuthComponent looks OK. Can't guess what's wrong with it without debugging. I'll try it later.

**Comment by Ribesg** [comment]
Thanks. To start the project, run `build` on the `server` module and run the produced jar in `server/build`. The error occurs when I hit the login button after setting the fields. I tried randomly transforming the `Button` component into a functional component even if it doesn't make sense but no luck. Maybe it's caused by my usage of coroutines, I don't know :-/

**Comment by Ribesg** [comment]
I think it was a problem with things not being recompiled. Over time I updated various dependencies but it kept failing. Today I recloned the project on another computer and it works ¯\\\_(ツ)\_/¯
