### ISSUE TITLE
Add setState helper function

### ISSUE THREAD

**Issue by hofi99** [JetBrains/kotlin-wrappers#1290]
When using class components with the new kotlin-react there is no longer the [setState helper function](https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-react-legacy/src/main/kotlin/react/Component.ext.kt) available:
```
fun <S : State> Component<*, S>.setState(buildState: S.() -> Unit) {
    setState({ assign(it, buildState) })
}
```
Since class components are still part of react (and also the kotlin-react-core wrapper) it doesn't make sense to put this function in kotlin-react-legacy. 

Calling the "real" setState function isn't as convenient, so it would be really helpful to have this function not in kotlin-react-legacy but somewhere in kotlin-react or kotlin-react-core instead. 
Adding the legacy dependency to our projects also does not seem fitting because we are migrating to the new ChildrenBuilder pattern and don't want to use any of the legacy RBuilder.

Comparison:
```
// actual setState
setState(transformState = { assign(it, builder = { someState = false }) })
// or
setState(partialState = state.apply { someState = false })
```
vs.
```
// helper function
setState { someState = false }
```

**Comment by sgrishchenko** [comment]
@hofi99 thank you for suggestion, but we don't plan to support Class Components a lot and add sugar for them, our recommendation is moving to Function Components. 
Also if you remove all named params from you example it will look much more compact:
```kotlin
setState({ assign(it) { someState = false } })

setState(state.apply { someState = false })
```

And we recommend not to use `apply` for state because react does not like state mutation, so `assign` is more safe solution here
```
setState(assign(state) { someState = false })
```
