### ISSUE TITLE
CSS-in-JS for kotlin-react 

### ISSUE THREAD

**Issue by jfontsaballs** [JetBrains/kotlin-wrappers#1521]
From [this](https://github.com/JetBrains/kotlin-wrappers/blob/master/CHANGELOG.md#pre282) I assume that you recommend using `kotlin-react` for new projects, leaving `kotlin-react-legacy` only for compatibility with existing projects.

However, I haven't been able to find which CSS-in-JS library do you recommend for using with the new `kotlin-react` library. I tried using `kotlin-styled-next` but after some failed tests and a bit of code reading I have come to believe that it can only be used with `kotlin-react-legacy`, am I right? So with `kotlin-react` we have to use `kotlin-emotion`, right?

If this is the case, I would kindly request you modify the documentation of those projects to clearly state these facts. 

Finally, just out of curiosity, I would like to know the reason behind the move from `styled-components` to `emotion`.

Thank-you very much.

**Comment by turansky** [comment]
> So with kotlin-react we have to use kotlin-emotion, right?

Right

> Finally, just out of curiosity, I would like to know the reason behind the move from `styled-components` to `emotion`

Emotion implements API, required for fine DSL:
* CSS object -> `ClassName` (`emotion.css.css`) // missed in `styled-components`
* Slyled component (`emotion.styled.styled`)

**Comment by Leonya** [comment]
Thanks, we will update the documentation. `kotlin-styled-next` is, in fact, not a wrapper for `styled-components`, it's a clean-slate reimplementation. We created it at JetBrains because we believed we could do better. We will continue improving it now that the Kotlin/JS IR compiler is almost stable. On the other hand, we don't have the resources to migrate to the new React DSL implemented in `kotlin-react`, because our codebase is too large. Hence two branches.
