### ISSUE TITLE
Missing Route props in react-router after upgrade to -pre.499

### ISSUE THREAD

**Issue by Coneys** [JetBrains/kotlin-wrappers#1921]
Hello, after upgrading wrapper "kotlin-react-router-dom" to version -pre.499 RouteProps (path and element) are missing. Before upgrade it looked like this:

```
HashRouter {

        Routes {
            Route {
                path = "/"
                element = buildElement {
                    ...
                }
            }
        }
    }
```

Now both "path" and "element" props are missing. Declaration look like this:

`external interface RouteProps : react.Props /* export declare type RouteProps = PathRouteProps | LayoutRouteProps | IndexRouteProps; */`

I am pretty sure its just bug of generator, because I can still access and modify those Props by using "asDynamic":

```
Routes {
        Route {
            asDynamic().path = "/"
            asDynamic().element = buildElement {
                ...
            }
        }
    }
```

**Comment by turansky** [comment]
It's already fixed in `master` branch and will be released soon.
Recommendation for now - use `kotlin-react-router-dom-legacy`.

**Comment by dioxic** [comment]
Still causing a problem on pre545 for me too.

**Comment by turansky** [comment]
Modern solution - use `createBrowserRouter` [like in example](https://github.com/JetBrains/kotlin-wrappers/blob/d036a00cbe622f9dc7ae2ee5e5232b669a91563c/examples/src/jsMain/kotlin/example/ReactRouterDom.kt#L96). It definitely works - I use it my projects.

Example with `createHashRouter` [is here](https://github.com/karakum-team/kotlin-mui-showcase/blob/1aef7b57047f1f1964f6dc1f8e2d13af064a3f29/src/main/kotlin/team/karakum/App.kt#L22)

In last declarations `Component` property can be used instead of `element`.

**Comment by turansky** [comment]
> Do both paths need to be added in createBrowserRouter at the beginning?

You can do like this:
```kotlin
val App = VFC {
    val access = useUserAccess()
    
    val routes = useUserRoutes(access)
    
    val router = createBrouserRouter(routes)
    
    // components
}
```

**Comment by turansky** [comment]
I use `matchPath` for such checks
