### ISSUE TITLE
Node's Socket.destroy argument should be optional

### ISSUE THREAD

**Issue by lppedd** [JetBrains/kotlin-wrappers#2203]
The Node's `Socket.destroy()` method should accept an __optional__ `error` argument, as per signature.

```
socket.destroy([error])
```

Right now it is mandatory, so one is forced to use `asDynamic`.

**Comment by sgrishchenko** [comment]
Thank you a lot for reporting this.

It is a tricky thing because both `Readable` and `Writable` declare `destroy` method, that has optional parameter (that converts as default parameter in Kotlin). Kotlin compiler is not smart enough to guess that both parameters have the same default value and this value even won't be used in runtime, so it actually says: "In `Duplex` class you have a method with a default parameter, that could have different values in runtime, so when you call this method without parameter, I don't know which value to use a default: from `Readable` or from `Writable`".

As a workaround, I injected to `Readable`, `Writable` and `Duplex` `destroy` method without parameters.

For future, actually, there are 3 `Socket` types in Node :slightly_smiling_face: 
* `node.dgram.Socket`
* `node.net.Socket`
* `node.process.Socket`

Could you be more precise in naming, because it will save me some time to fix such problems?

**Comment by lppedd** [comment]
Ah yes you're right, I got so used to working `net.Socket` that I forgot about the others!

Thanks for the fix!
