### ISSUE TITLE
Default parameter flexBasis of function flex must be 0%

### ISSUE THREAD

**Issue by Nagatsuka-Akiya** [JetBrains/kotlin-wrappers#234]

**Comment by Leonya** [comment]
`flexBasis` is set conditionally, so not setting it means that the default value will be used.

**Comment by NagatsukaAyako** [comment]
Ok, but it's some unexpected, because if someone uses function `flex,` he think it is equvalent of css `flex` with 3 values. But this CSS property is strange. `flex-basis` default value is auto, but css code `flex: 1;` set `flex-basis` to 0%.

**Comment by Leonya** [comment]
I agree, it would be best to set the shorthand property instead. I'll make the change.

**Comment by Leonya** [comment]
I have changed the implementation of the `flex` function to set the `flex` shorthand property rather than `flex-grow`, `flex-shrink` and `flex-basis` separately, but I didn't change the default value of `flex-basis` as that would be a breaking change that could be hard to catch and fix.

So, when you call `flex(1)` it would set `flex: 1 1 auto`, not `flex: 1`.
