### ISSUE TITLE
Unclear if I need to include `StyleSheet` object somewhere

### ISSUE THREAD

**Issue by jonnyzzz** [JetBrains/kotlin-wrappers#58]
Documentation does not say anything regarding that. Will my `StyleSheet` object register itself? Do I need to register is somewhere?

**Comment by chadmorrow-fd** [comment]
If you're using styled components then the styles will be inserted into the head tag of your page at run time. 

For example, if I have something like this in my render...

```kotlin
override fun RBuilder.render() {
        val errors = validate(inputs = state.firstName)
        styledDiv {
            css { +Styles.root }
          
// etc. etc.
```

and then somewhere else in that file outside of the component I have my styles written out like...
```kotlin
object Styles : StyleSheet("Styles") {
    val root by css {
        paddingTop = 50.px
        display = Display.flex
        alignItems = Align.center
        justifyContent = JustifyContent.center
        fontFamily = "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto,Oxygen-Sans,Ubuntu, Cantarell, \"Helvetica Neue\", sans-serif"
        fontSize = 18.px
    }
```

then that's all I need to do in order to have my styles work.

**Comment by Leonya** [comment]
Updated the documentation.
