### ISSUE TITLE
Cannot connect component with kotlin-react-redux

### ISSUE THREAD

**Issue by gkdevone** [JetBrains/kotlin-wrappers#79]
Regarding the kotlin-react-redux wrapper

we cannot connect a component with

`rConnect(...) : (RClass<P>) -> RClass<OP> `

In order to connect someComponent then someComponent should be of type RClass in order to call rConnect(...)(someComponent)

Can you pls advise how to connect each of the components below?

```
fun RBuilder.componentA() {
    + "test function component"
}

class ComponentB(props: RProps) : RComponent<RProps, RState>(props) {
    override fun RBuilder.render() {
        + "test class component"
    }
}
```

Also after connecting ComponentB how should we call the RBuilder.child(...) in order to render the connectedComponentB?

**Comment by Leonya** [comment]
@Jamdan2 can you assist?

**Comment by Jamdan2** [comment]
Well, you cannot connect a kotlin functional component, so if you need to connect a component you should use a class.

As for the class component, you need to get the javascript class, which can be converted into an RClass.

To use it, you actually don't need to call `RBuilder.child` at all, the connected component is ready to use as is. Here's how you would connect and use your `ComponentB`:

```
val connectedComponentB = connect(...)(ComponentB::class.js as RClass<RProps>)

render(...) {
	connectedComponentB {}
}
```

On a side note, ComponentB should not take props as a constructor parameter, because props are handled by the dsl.

**Comment by Hypnosphi** [comment]
> cannot connect a kotlin functional component

Can we support that? shouldn't bee too hard, you probably just need to add an `invoke` overload and wrap the input with `rFunction`

**Comment by Hypnosphi** [comment]
Or you can even declare the `connect` return value as having type `rHOC<P, OP>`, it already has all the needed overloads: https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-react/src/main/kotlin/react/HOC.kt

**Comment by Jamdan2** [comment]
Done, a pull request is up for it now

**Comment by Leonya** [comment]
Thanks, merged!
